Added new Reusable Button
Dezenix/frontend-reactjs pull request #26
Opened 2021-12-20 12:49 UTC by ehteshaxm

2021-12-21 11:37 UTC, Ovenoboyo requested changes
Please take a look at how other components have been implemented. Your component does not build neither have you provided an example implementation in the example directory.

You can read the README.md of this repo for further clarification. If you have any more questions you can ask them on [discord](https://discord.gg/crZWFkXe)

2021-12-21 13:19 UTC, Ovenoboyo requested changes

2021-12-21 13:19 UTC, Ovenoboyo commented on example/src/components/Home.js
>            {/* Add new Link Here for your new component */}
You're supposed to add your component here. Please check how other components have been implemented

2021-12-21 13:19 UTC, Ovenoboyo commented on example/src/components/button/button.module.css
> +.btn {
unnecessary file

2021-12-21 13:19 UTC, Ovenoboyo commented on example/src/components/button/index.js
> +import React from 'react'
unnecessary file

2021-12-21 13:19 UTC, Ovenoboyo commented on example/src/components/Home.js
>            {/* Add new Link Here for your new component */}
Check App.js in src/example for more details

2021-12-21 13:21 UTC, Ovenoboyo requested changes

2021-12-21 13:21 UTC, Ovenoboyo commented on example/src/components/Home.js
> +      <Button />
Please dont unnecessarily add your component in Home.js

2021-12-27 11:13 UTC, ehteshaxm commented
I am getting an error that my component is not being imported from denezix-react in App.js inside example

2021-12-27 11:33 UTC, Ovenoboyo commented
Can you show us what you've tried?

> I am getting an error that my component is not being imported from denezix-react in App.js inside example

2021-12-27 11:41 UTC, ehteshaxm commented
I compiled again its working now.....

2021-12-27 11:44 UTC, ehteshaxm commented
Please End this request I created a new one

2021-12-27 11:45 UTC, closed without merging